// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieReviews.Data;

#nullable disable

namespace MovieReviews.Migrations
{
    [DbContext(typeof(MovieReviewDBContext))]
    [Migration("20230802122847_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MovieReviews.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Review")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
                            ImageUrl = "/images/movies/Highlander.png",
                            Review = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam quam erat, gravida quis est vitae, tempus dignissim lorem. Vestibulum et aliquam est. Phasellus interdum diam ac faucibus condimentum. In malesuada scelerisque blandit.",
                            Title = "Highlander"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
                            ImageUrl = "/images/movies/Godfather.png",
                            Review = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam quam erat, gravida quis est vitae, tempus dignissim lorem. Vestibulum et aliquam est. Phasellus interdum diam ac faucibus condimentum. In malesuada scelerisque blandit.",
                            Title = "Godfather"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
                            ImageUrl = "/images/movies/LastOfTheMohicans.png",
                            Review = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam quam erat, gravida quis est vitae, tempus dignissim lorem. Vestibulum et aliquam est. Phasellus interdum diam ac faucibus condimentum. In malesuada scelerisque blandit.",
                            Title = "Last of the Mohicans"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
                            ImageUrl = "/images/movies/RearWindow.png",
                            Review = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam quam erat, gravida quis est vitae, tempus dignissim lorem. Vestibulum et aliquam est. Phasellus interdum diam ac faucibus condimentum. In malesuada scelerisque blandit.",
                            Title = "Rear Window"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
                            ImageUrl = "/images/movies/RoadHouse.png",
                            Review = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam quam erat, gravida quis est vitae, tempus dignissim lorem. Vestibulum et aliquam est. Phasellus interdum diam ac faucibus condimentum. In malesuada scelerisque blandit.",
                            Title = "Road House"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
                            ImageUrl = "/images/movies/StarTreck4.png",
                            Review = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam quam erat, gravida quis est vitae, tempus dignissim lorem. Vestibulum et aliquam est. Phasellus interdum diam ac faucibus condimentum. In malesuada scelerisque blandit.",
                            Title = "Star Trek IV"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
